In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [ ]:
df=pd.read_csv('/content/Book 21(Sheet1).csv')
df

Area  Unnamed: 1  bedrooms  Unnamed: 3  age of house  Unnamed: 5   price
0  2600         NaN       3.0         NaN            20         NaN  550000
1  3000         NaN       4.0         NaN            15         NaN  565000
2  3200         NaN       NaN         NaN            18         NaN  610000
3  3600         NaN       3.0         NaN            30         NaN  595000
4  4000         NaN       5.0         NaN             8         NaN  760000

Datapreprocessing-Handling NA values

In [ ]:
#calculating median
median_bedrooms = df['bedrooms'].median()
print(median_bedrooms)

3.5


In [ ]:
#we did floor so we get integers

In [ ]:
df['bedrooms'] = df['bedrooms'].fillna(median_bedrooms)
df['bedrooms'] = df['bedrooms'].apply(np.floor)
df['bedrooms'] = df['bedrooms'].astype(int)
display(df)

Area  Unnamed: 1  bedrooms  Unnamed: 3  age of house  Unnamed: 5   price
0  2600         NaN         3         NaN            20         NaN  550000
1  3000         NaN         4         NaN            15         NaN  565000
2  3200         NaN         3         NaN            18         NaN  610000
3  3600         NaN         3         NaN            30         NaN  595000
4  4000         NaN         5         NaN             8         NaN  760000

In [ ]:
reg=linear_model.LinearRegression()
reg.fit(df[['Area','bedrooms','age of house']],df.price)

LinearRegression()

In [ ]:
#predicting
reg.predict([[3000,3,40]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [ ]:
reg.coef_ #m1,m2,m3

array([   137.25, -26025.  ,  -6825.  ])

In [ ]:
reg.intercept_

np.float64(383724.9999999998)

In [ ]:
#calcualted
area,age,bedrooms=3000,3,40
m1,m2,m3=reg.coef_
b=reg.intercept_
y=m1*area+m2*age+m3*bedrooms+b
y

np.float64(444400.0)

hence we get predicted almost similar to calculated


implementing gradient descent


In [ ]:
def gradient_descent(x,y):
  m_curr=b_curr=0
  iterations=10
  n=len(x)
  learning_rate=0.01
  for i in range(iterations):
    y_predicted=m_curr*x+b_curr
    cost=(1/n)+sum([val**2 for val in(y-y_predicted)])#to handle engative values
    m_derivative=-(2/n)*sum(x*y-y_predicted)
    b_derivative=-(2/n)*sum(y-y_predicted)
    m_curr=m_curr-learning_rate*m_derivative
    b_curr=b_curr-learning_rate*b_derivative
    print("m {}, b{},cost{}, iteration{}".format(m_curr,b_curr,i,cost))
x=np.array([1,2,3,4,5])
y=np.array([5,7,9,11,13])
gradient_descent(x,y)

#According to our need we change iterations and learning rate

m 0.62, b0.18,cost0, iteration445.2
m 1.1992, b0.3192,cost1, iteration261.45199999999994
m 1.7408640000000002, b0.420864,cost2, iteration135.80741759999998
m 2.2479948800000003, b0.48799488,cost3, iteration57.203452784639985
m 2.7233552896, b0.5233552896,cost4, iteration16.444496693559277
m 3.169486866432, b0.5294868664319999,cost5, iteration5.902381680506989
m 3.58872791711744, b0.5087279171174399,cost6, iteration19.26367001562526
m 3.983229683748045, b0.46322968374804474,cost7, iteration51.31667944298254
m 4.354971309048201, b0.39497130904820116,cost8, iteration97.77207124329678
m 4.705773604324345, b0.305773604324345,cost9, iteration155.11178026445478


Handling dummy values


In [3]:
import pandas as pd

In [5]:
df=pd.read_csv('/content/Book 22(Sheet1).csv')
df

town  Unnamed: 1   Area  Unnamed: 3  Unnamed: 4    price
0     a         NaN   9000         NaN         NaN   980000
1     a         NaN   8000         NaN         NaN     9700
2     a         NaN   7999         NaN         NaN  6788888
3     b         NaN      7         NaN         NaN    67888
4     b         NaN   7777         NaN         NaN    99998
5     b         NaN  55555         NaN         NaN     5000
6     b         NaN   6666         NaN         NaN   800000
7     c         NaN   3333         NaN         NaN   900000
8     c         NaN   2222         NaN         NaN  2900000
9     c         NaN   1234         NaN         NaN   300000
10    c         NaN   2222         NaN         NaN     4000
11    c         NaN  44444         NaN         NaN   444445

In [6]:
dummies=pd.get_dummies(df.town)#to return dummy values
dummies

a      b      c
0    True  False  False
1    True  False  False
2    True  False  False
3   False   True  False
4   False   True  False
5   False   True  False
6   False   True  False
7   False  False   True
8   False  False   True
9   False  False   True
10  False  False   True
11  False  False   True

In [ ]:
merged=pd.concat([df,dummies],axis='columns')
merged

town  Unnamed: 1   Area  Unnamed: 3  Unnamed: 4    price      a      b  \
0     a         NaN   9000         NaN         NaN   980000   True  False   
1     a         NaN   8000         NaN         NaN     9700   True  False   
2     a         NaN   7999         NaN         NaN  6788888   True  False   
3     b         NaN      7         NaN         NaN    67888  False   True   
4     b         NaN   7777         NaN         NaN    99998  False   True   
5     b         NaN  55555         NaN         NaN     5000  False   True   
6     b         NaN   6666         NaN         NaN   800000  False   True   
7     c         NaN   3333         NaN         NaN   900000  False  False   
8     c         NaN   2222         NaN         NaN  2900000  False  False   
9     c         NaN   1234         NaN         NaN   300000  False  False   
10    c         NaN   2222         NaN         NaN     4000  False  False   
11    c         NaN  44444         NaN         NaN   444445  False  False   

        c  
0   False  
1   False  
2   False  
3   False  
4   False  
5   False  
6   False  
7    True  
8    True  
9    True  
10   True  
11   True

In [ ]:
#you have to remove one of the dummy value
final=merged.drop(['town','b'], axis='columns')# b town dropped
final

Unnamed: 1   Area  Unnamed: 3  Unnamed: 4    price      a      c
0          NaN   9000         NaN         NaN   980000   True  False
1          NaN   8000         NaN         NaN     9700   True  False
2          NaN   7999         NaN         NaN  6788888   True  False
3          NaN      7         NaN         NaN    67888  False  False
4          NaN   7777         NaN         NaN    99998  False  False
5          NaN  55555         NaN         NaN     5000  False  False
6          NaN   6666         NaN         NaN   800000  False  False
7          NaN   3333         NaN         NaN   900000  False   True
8          NaN   2222         NaN         NaN  2900000  False   True
9          NaN   1234         NaN         NaN   300000  False   True
10         NaN   2222         NaN         NaN     4000  False   True
11         NaN  44444         NaN         NaN   444445  False   True

In [ ]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [ ]:
#x is to get all independent varaibles which are needed for trainning
#so to get all independent variables we have to drop dependent variable
X=final.drop('price',axis='columns')
X

Unnamed: 1   Area  Unnamed: 3  Unnamed: 4      a      c
0          NaN   9000         NaN         NaN   True  False
1          NaN   8000         NaN         NaN   True  False
2          NaN   7999         NaN         NaN   True  False
3          NaN      7         NaN         NaN  False  False
4          NaN   7777         NaN         NaN  False  False
5          NaN  55555         NaN         NaN  False  False
6          NaN   6666         NaN         NaN  False  False
7          NaN   3333         NaN         NaN  False   True
8          NaN   2222         NaN         NaN  False   True
9          NaN   1234         NaN         NaN  False   True
10         NaN   2222         NaN         NaN  False   True
11         NaN  44444         NaN         NaN  False   True

In [ ]:
Y=final.price
Y

0      980000
1        9700
2     6788888
3       67888
4       99998
5        5000
6      800000
7      900000
8     2900000
9      300000
10       4000
11     444445
Name: price, dtype: int64

In [ ]:
# Drop columns where more than 50% values are NaN
X = X.dropna(thresh=len(X) // 2, axis=1)
#if there are NAN values we are unable to train model

In [ ]:
model.fit(X,Y)#training model


LinearRegression()

In [ ]:
import numpy as np
model.predict(np.array([44444,0,1]).reshape(1, -1))#predicting values

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([598257.5818972])

In [ ]:
model.score(X,Y)#my model is only 23 % right because the dataset is improer

0.23760474642531415

In [ ]:
df

town  Unnamed: 1   Area  Unnamed: 3  Unnamed: 4    price
0     a         NaN   9000         NaN         NaN   980000
1     a         NaN   8000         NaN         NaN     9700
2     a         NaN   7999         NaN         NaN  6788888
3     b         NaN      7         NaN         NaN    67888
4     b         NaN   7777         NaN         NaN    99998
5     b         NaN  55555         NaN         NaN     5000
6     b         NaN   6666         NaN         NaN   800000
7     c         NaN   3333         NaN         NaN   900000
8     c         NaN   2222         NaN         NaN  2900000
9     c         NaN   1234         NaN         NaN   300000
10    c         NaN   2222         NaN         NaN     4000
11    c         NaN  44444         NaN         NaN   444445

  One hot label encoding
  

In [9]:
from sklearn.preprocessing  import LabelEncoder
le=LabelEncoder()#objectcreation

In [10]:
dfle=df
#returning labels
le.fit_transform(dfle.town)
dfle

town  Unnamed: 1   Area  Unnamed: 3  Unnamed: 4    price
0     a         NaN   9000         NaN         NaN   980000
1     a         NaN   8000         NaN         NaN     9700
2     a         NaN   7999         NaN         NaN  6788888
3     b         NaN      7         NaN         NaN    67888
4     b         NaN   7777         NaN         NaN    99998
5     b         NaN  55555         NaN         NaN     5000
6     b         NaN   6666         NaN         NaN   800000
7     c         NaN   3333         NaN         NaN   900000
8     c         NaN   2222         NaN         NaN  2900000
9     c         NaN   1234         NaN         NaN   300000
10    c         NaN   2222         NaN         NaN     4000
11    c         NaN  44444         NaN         NaN   444445

In [12]:
x=df[['town','Area']]
x

array([['a', 9000],
       ['a', 8000],
       ['a', 7999],
       ['b', 7],
       ['b', 7777],
       ['b', 55555],
       ['b', 6666],
       ['c', 3333],
       ['c', 2222],
       ['c', 1234],
       ['c', 2222],
       ['c', 44444]], dtype=object)

In [13]:
y=dfle.price
y

0      980000
1        9700
2     6788888
3       67888
4       99998
5        5000
6      800000
7      900000
8     2900000
9      300000
10       4000
11     444445
Name: price, dtype: int64

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer([('town', OneHotEncoder(), [0])], remainder='passthrough')

In [21]:
import numpy as np

In [23]:
x = ct.fit_transform(x)


In [25]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x,y)

LinearRegression()